-- 코드를 작성해주세요
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_TREE IT
JOIN ITEM_INFO P ON IT.PARENT_ITEM_ID = P.ITEM_ID
JOIN ITEM_INFO II ON II.ITEM_ID = IT.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY II.ITEM_ID DESC;
